<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Cate extends Model
{
    protected $table = "cate";

    protected $fillable = [
        'title',
        'slug',
        'type_slug',
        'sort'
    ];

    public function scopePriority($query) {
        return $query->orderBy('sort','desc');
    }

    public function products() {
        return $this->belongsToMany(Product::class,'product_cate','cate_id','product_id');
    }

    public function visibleProducts() {
        return $this->belongsToMany(Product::class,'product_cate','cate_id','product_id')
            ->where('status',Product::STATUS_VISIBLE)
            ->orderBy('sort','desc');
    }

    public function forgetCache($model) {
        if(Cache::has("accessories")) {
            Cache::forget("accessories");
        }
        if($model && Cache::has("accessories".$model->slug)) {
            Cache::forget("accessories".$model->slug);
        }
    }


    public static function booted()
    {
        static::created(function ($model) {
            $this->forgetCache($model);
        });

        static::updated(function ($model) {
            $this->forgetCache($model);
        });
        static::deleted(function ($model) {
            $this->forgetCache($model);
        });

        parent::booted(); // TODO: Change the autogenerated stub
    }

}
