<?php

namespace App\Models;

use App\Application;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;

class Product extends Model
{

    public const STATUS_VISIBLE = 0;
    public const STATUS_INVISIBLE = 1;

    protected $table = "product";

    protected $fillable = [
        "title",
        "sku",
        "slug",
        "price",
        "thumb",
        "software",
        "status",
        "images",
        "content",
        "intro",
        "description",
        "feature",
        "specification",
        "package",
        "downloads",
        "videos",
        "sort"
    ];

    protected $casts = [
        'images' => 'array',
        'downloads' => 'array',
        'videos' => 'array',
        'software' => 'array',
    ];

    public function setImagesAttribute($value) {
        $this->attributes['images'] = json_encode(json_decode($value), true);
    }
    public function setDownloadsAttribute($value) {
        $this->attributes['downloads'] = json_encode(json_decode($value), true);
    }
    public function setVideosAttribute($value) {
        $this->attributes['videos'] = json_encode(json_decode($value), true);
    }
    public function setSoftwareAttribute($value) {
        $this->attributes['software'] = json_encode(json_decode($value), true);
    }

    public function cates() {
        return $this->belongsToMany(Cate::class,'product_cate','product_id','cate_id')->withTimestamps();
    }


    public function scopeActive($query) {
        return $query->whereIn("status", [self::STATUS_VISIBLE,self::STATUS_INVISIBLE]);
    }

    public function scopeVisible($query) {
        return $query->where("status", self::STATUS_VISIBLE);
    }

    public function scopePriority($query) {
        return $query->orderBy('sort','desc');
    }

    /**
     * Clear cache - make this static since it's called from static methods
     */
    public static function forgetCache($model = null) {
        try {
            Artisan::call("cache:clear");

        } catch (\Exception $e) {
            Log::error('Failed to clear product cache', [
                'error' => $e->getMessage(),
                'model_id' => $model ? $model->id : null
            ]);
        }
    }

    public static function booted()
    {
        static::created(function ($model) {
            static::forgetCache($model);
      });

        static::updated(function ($model) {
            static::forgetCache($model);
        });
        static::deleted(function ($model) {
            static::forgetCache($model);
        });

        parent::booted(); // TODO: Change the autogenerated stub
    }

}
